cleanup Paramore.Brighter.Outbox.PostgreSql
BrighterCommand/Brighter pull request #2597
Opened 2023-04-04 10:01 UTC by SimonCropp

2023-04-04 18:02 UTC, iancooper approved these changes

2023-04-05 08:46 UTC, iancooper requested changes

2023-04-05 08:46 UTC, iancooper commented on src/Paramore.Brighter.Outbox.PostgreSql/PostgreSqlOutboxSync.cs
> +                using var command = InitMarkDispatchedCommand(connection, id, dispatchedAt);
You can't use Using Declarations as we are C# 7.3 due to supporting .NET Standard 2.0 if you look in the file section of GitHub you should be able to see the build errors against the files.

(We support netstandard20 as this gives us framework and core support. Dropping framework support is something we might consider in V10, but the principle of a library being as compatible as important remains important to us)

2023-04-20 09:26 UTC, iancooper commented
We have changes that will impact this one, as we are moving PostgreSql to the same model as other Outboxes. I am going to close this one as a result.

2023-04-20 09:26 UTC, closed without merging

2023-04-20 10:33 UTC, SimonCropp commented
@iancooper no worries. do you want more of these type of prs?

2023-04-21 20:38 UTC, iancooper commented
Happy to keep taking PRs. This one just collided with a major restructuring of that code.